# Site title and subtitle. This is used in _includes/header.html
title: 'LostGrid'
subtitle: 'LostGrid is a powerful grid system built in PostCSS that works with any preprocessor and even vanilla CSS.'
url: 'http://lostgrid.org'

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-71789679-1'


# Version of LostGrid this is targeted for:
docs-version: '8.2.0'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/peterramsing/lost'

# Default categories (in order) to appear in the navigation
sections: [
  ['doc', 'Documentation'],
  ['tut', 'Tutorial'],
  ['ref', 'Reference'],
  ['dev', 'Developers'],
  ['post', 'Posts']
]

# Collections for the documentation to live
collections:
  docs:

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
  extensions: [
    'no_intra_emphasis',
    'fenced_code_blocks',
    'autolink',
    'strikethrough',
    'superscript',
    'with_toc_data',
    'tables',
    'hardwrap'
  ]

# Gem
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
